using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MyClub.Services.Database.Seeders
{
    public static class AssetSeeder
    {
        public static void SeedData(this EntityTypeBuilder<Asset> entity)
        {
            entity.HasData(
                new Asset { Id = 1, Url = "https://nihadfit.blob.core.windows.net/news/1.jpg" },
                new Asset { Id = 2, Url = "https://nihadfit.blob.core.windows.net/news/2.jpg" },
                new Asset { Id = 3, Url = "https://nihadfit.blob.core.windows.net/news/3.jpg" },
                new Asset { Id = 4, Url = "https://nihadfit.blob.core.windows.net/news/4.jpg" },
                new Asset { Id = 5, Url = "https://nihadfit.blob.core.windows.net/news/5.jpg" },
                new Asset { Id = 6, Url = "https://nihadfit.blob.core.windows.net/news/6.jpg" },
                new Asset { Id = 7, Url = "https://nihadfit.blob.core.windows.net/news/7.jpg" },
                new Asset { Id = 8, Url = "https://nihadfit.blob.core.windows.net/news/8.jpg" },
                new Asset { Id = 9, Url = "https://nihadfit.blob.core.windows.net/news/9.jpg" },
                new Asset { Id = 10, Url = "https://nihadfit.blob.core.windows.net/news/10.jpg" },
                new Asset { Id = 11, Url = "https://nihadfit.blob.core.windows.net/news/11.jpg" },
                new Asset { Id = 12, Url = "https://nihadfit.blob.core.windows.net/news/12.jpg" },
                new Asset { Id = 13, Url = "https://nihadfit.blob.core.windows.net/news/13.jpg" },
                new Asset { Id = 14, Url = "https://nihadfit.blob.core.windows.net/news/14.jpg" },
                new Asset { Id = 15, Url = "https://nihadfit.blob.core.windows.net/news/15.jpg" },
                new Asset { Id = 16, Url = "https://nihadfit.blob.core.windows.net/news/16.jpg" },
                new Asset { Id = 17, Url = "https://nihadfit.blob.core.windows.net/news/17.jpg" },
                new Asset { Id = 18, Url = "https://nihadfit.blob.core.windows.net/news/18.jpg" },
                new Asset { Id = 19, Url = "https://nihadfit.blob.core.windows.net/news/19.jpg" },
                new Asset { Id = 20, Url = "https://nihadfit.blob.core.windows.net/news/20.jpg" },
                new Asset { Id = 21, Url = "https://nihadfit.blob.core.windows.net/news/21.jpg" },
                new Asset { Id = 22, Url = "https://nihadfit.blob.core.windows.net/news/22.jpg" },
                new Asset { Id = 23, Url = "https://nihadfit.blob.core.windows.net/news/23.jpg" },
                new Asset { Id = 24, Url = "https://nihadfit.blob.core.windows.net/news/24.jpg" },
                new Asset { Id = 25, Url = "https://nihadfit.blob.core.windows.net/news/25.jpg" },
                new Asset { Id = 26, Url = "https://nihadfit.blob.core.windows.net/news/26.jpg" },
                new Asset { Id = 27, Url = "https://nihadfit.blob.core.windows.net/news/27.jpg" },
                new Asset { Id = 28, Url = "https://nihadfit.blob.core.windows.net/news/28.jpg" },
                new Asset { Id = 29, Url = "https://nihadfit.blob.core.windows.net/news/29.jpg" },
                new Asset { Id = 30, Url = "https://nihadfit.blob.core.windows.net/news/30.jpg" },
                new Asset { Id = 31, Url = "https://nihadfit.blob.core.windows.net/news/31.jpg" },
                new Asset { Id = 32, Url = "https://nihadfit.blob.core.windows.net/news/32.jpg" },
                new Asset { Id = 33, Url = "https://nihadfit.blob.core.windows.net/news/33.jpg" },
                new Asset { Id = 34, Url = "https://nihadfit.blob.core.windows.net/news/34.jpg" },
                new Asset { Id = 35, Url = "https://nihadfit.blob.core.windows.net/news/35.jpg" },
                new Asset { Id = 36, Url = "https://nihadfit.blob.core.windows.net/news/36.jpg" },
                new Asset { Id = 37, Url = "https://nihadfit.blob.core.windows.net/news/37.jpg" },
                new Asset { Id = 38, Url = "https://nihadfit.blob.core.windows.net/news/38.jpg" },
                new Asset { Id = 39, Url = "https://nihadfit.blob.core.windows.net/news/39.jpg" },
                new Asset { Id = 40, Url = "https://nihadfit.blob.core.windows.net/news/40.jpg" },

                //Asset for Products
                new Asset { Id = 41, Url = "https://nihadfit.blob.core.windows.net/products/1.jpg" },
                new Asset { Id = 42, Url = "https://nihadfit.blob.core.windows.net/products/2.jpg" },
                new Asset { Id = 43, Url = "https://nihadfit.blob.core.windows.net/products/3.jpg" },
                new Asset { Id = 44, Url = "https://nihadfit.blob.core.windows.net/products/4.jpg" },
                new Asset { Id = 45, Url = "https://nihadfit.blob.core.windows.net/products/5.jpg" },
                new Asset { Id = 46, Url = "https://nihadfit.blob.core.windows.net/products/6.jpg" },
                new Asset { Id = 47, Url = "https://nihadfit.blob.core.windows.net/products/7.jpg" },
                new Asset { Id = 48, Url = "https://nihadfit.blob.core.windows.net/products/8.jpg" },
                new Asset { Id = 49, Url = "https://nihadfit.blob.core.windows.net/products/9.jpg" },
                new Asset { Id = 50, Url = "https://nihadfit.blob.core.windows.net/products/10.jpg" },
                new Asset { Id = 51, Url = "https://nihadfit.blob.core.windows.net/products/11.jpg" },
                new Asset { Id = 52, Url = "https://nihadfit.blob.core.windows.net/products/12.jpg" },
                new Asset { Id = 53, Url = "https://nihadfit.blob.core.windows.net/products/13.jpg" },
                new Asset { Id = 54, Url = "https://nihadfit.blob.core.windows.net/products/14.jpg" },
                new Asset { Id = 55, Url = "https://nihadfit.blob.core.windows.net/products/15.jpg" },
                new Asset { Id = 56, Url = "https://nihadfit.blob.core.windows.net/products/16.jpg" },
                new Asset { Id = 57, Url = "https://nihadfit.blob.core.windows.net/products/17.jpg" },
                new Asset { Id = 58, Url = "https://nihadfit.blob.core.windows.net/products/18.jpg" },
                new Asset { Id = 59, Url = "https://nihadfit.blob.core.windows.net/products/19.jpg" },
                new Asset { Id = 60, Url = "https://nihadfit.blob.core.windows.net/products/20.jpg" },
                new Asset { Id = 61, Url = "https://nihadfit.blob.core.windows.net/products/21.jpg" },
                new Asset { Id = 62, Url = "https://nihadfit.blob.core.windows.net/products/22.jpg" },
                new Asset { Id = 63, Url = "https://nihadfit.blob.core.windows.net/products/23.jpg" },
                new Asset { Id = 64, Url = "https://nihadfit.blob.core.windows.net/products/24.jpg" },
                new Asset { Id = 65, Url = "https://nihadfit.blob.core.windows.net/products/25.jpg" },
                new Asset { Id = 66, Url = "https://nihadfit.blob.core.windows.net/products/26.jpg" },
                new Asset { Id = 67, Url = "https://nihadfit.blob.core.windows.net/products/27.jpg" },
                new Asset { Id = 68, Url = "https://nihadfit.blob.core.windows.net/products/28.jpg" },
                new Asset { Id = 69, Url = "https://nihadfit.blob.core.windows.net/products/29.jpg" },
                new Asset { Id = 70, Url = "https://nihadfit.blob.core.windows.net/products/30.jpg" },
                new Asset { Id = 71, Url = "https://nihadfit.blob.core.windows.net/products/31.jpg" },
                new Asset { Id = 72, Url = "https://nihadfit.blob.core.windows.net/products/32.jpg" },

                //Asset for club picture
                new Asset { Id = 73, Url = "hhttps://nihadfit.blob.core.windows.net/club/club.jpg" },
            
                //Asset for player picture
                new Asset { Id = 74, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_1.png" },
                new Asset { Id = 75, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_2.png" },
                new Asset { Id = 76, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_3.png" },
                new Asset { Id = 77, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_4.png" },
                new Asset { Id = 78, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_5.png" },
                new Asset { Id = 79, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_6.png" },
                new Asset { Id = 80, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_7.png" },
                new Asset { Id = 81, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_8.png" },
                new Asset { Id = 82, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_9.png" },
                new Asset { Id = 83, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_10.png" },
                new Asset { Id = 84, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_11.png" },
                new Asset { Id = 85, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_12.png" },
                new Asset { Id = 86, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_13.png" },
                new Asset { Id = 87, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_14.png" },
                new Asset { Id = 88, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_15.png" },
                new Asset { Id = 89, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_16.png" },
                new Asset { Id = 90, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_17.png" },
                new Asset { Id = 91, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_18.png" },
                new Asset { Id = 92, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_19.png" },
                new Asset { Id = 93, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_20.png" },
                new Asset { Id = 94, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_21.png" },
                new Asset { Id = 95, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_22.png" },
                new Asset { Id = 96, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_23.png" },
                new Asset { Id = 97, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_24.png" },
                new Asset { Id = 98, Url = "https://nihadfit.blob.core.windows.net/players/soccer_player_25.png" }

                
            );
        }
    }
}
